# Workflow name
name: Auto-testing-builds & Deployments

# This workflow is triggered on every push to the repository.
on:
  push:

# Defines the jobs that will be executed as part of this workflow.
jobs:
  create-testing-build:
    # We are using @feature/394-modular-workflows just for testing
    uses: awesomemotive/Botiga/.github/workflows/build.yml@feature/394-modular-workflows

  upload-testing-build:
    name: Prepare and upload builds in hub.wpforms.com/builds
    # Specifies the runner environment for the job. In this case, it\'s Ubuntu 22.04.
    runs-on: ubuntu-22.04

    # Defines the sequence of steps that make up the \'build\' job.
    steps:
      # This action exposes GitHub environment variables, making them available in subsequent steps.
      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v2.8.0

      # The following steps are for uploading the build to hub.wpforms.com.
      # Sets up an SSH key to securely connect to the deployment server.
      # The private key is stored as a secret.
      - name: Setup SSH key for hub.wpforms.com upload
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.WPFORMS_TEST_DOCKER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          chmod 700 ~/.ssh

      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ env.PROJECT_NAME }}
          path: ${{ env.PROJECT_NAME }}
      - run: zip -qq -r ${{ env.PROJECT_NAME }}.zip ${{ env.PROJECT_NAME }}

      # Creates the necessary directory structure on the local runner before uploading.
      - name: Create builds directory structure
        run: |
          mkdir -p builds/${{ env.PROJECT_NAME }}/${{ env.CI_REF_NAME_SLUG }}
          cp ${{ env.PROJECT_NAME }}.zip builds/${{ env.PROJECT_NAME }}/${{ env.CI_REF_NAME_SLUG }}/

      # Uploads the build to the deployment server using rsync over SSH.
      # --rsh: Specifies the remote shell to use (ssh with specific options).
      # -o StrictHostKeyChecking=no: Disables host key checking.
      # -p18765: Specifies the port for the SSH connection.
      # --ignore-times: Doesn\'t skip files that have the same size and modification time.
      # --archive: Archive mode, equivalent to -rlptgoD.
      # --verbose: Increases verbosity.
      # --compress: Compresses file data during the transfer.
      # --human-readable: Outputs numbers in a human-readable format.
      # --progress: Shows progress during transfer.
      # --whole-file: Copies files whole (without delta-xfer algorithm).
      # --remove-source-files: Removes files from the source directory after they are transferred.
      - name: Upload to hub.wpforms.com
        run: |
          rsync --rsh="ssh -o StrictHostKeyChecking=no -p18765" \
                --ignore-times \
                --archive \
                --verbose \
                --compress \
                --human-readable \
                --progress \
                --whole-file \
                --remove-source-files \
                builds/ \
                staging@34.68.130.55:/home/staging/shared/hub.wpforms.com/builds/athemes/